export * from './lib/FeaturesMail'
export { default as sendExternal } from './lib/handlers/sendExternal'
export { default as sendInternal } from './lib/handlers/sendInternal'
export { default as serializeMail } from './lib/handlers/serializeMail'
export { default as submitContactForm } from './lib/handlers/submitContactForm'
export { default as mailFormSchema } from './lib/schemas/mailForm'
export { default as mailOptionsSchema } from './lib/schemas/mailOptions'
export type { MailFormSchema, MailOptionsSchema, Sender } from './lib/schemas/types'
